version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newMusic
    depends_on:
      - db
      - migrate

  migrate:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newMusic
    entrypoint: ["npm", "run", "migrate"]
    depends_on:
      - db

  push:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newMusic
    entrypoint: ["npm", "run", "push"]
    depends_on:
      - db

  generate:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newMusic
    entrypoint: ["npm", "run", "generate"]
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newMusic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: